### ISSUE TITLE
Possible inconsistency between generated get_property and set_property! for Data

### ISSUE THREAD

**Issue by arunleob** [JamieMair/MuJoCo.jl#116]
I ran into an issue trying to set time, i.e. doing the following
```
using MuJoCo
model, data = MuJoCo.sample_model_and_data()
data.time = 10.0
display(data.time) # Displays 0
display(unsafe_load(Ptr{Float64}(data.internal_pointer + 100))) # Displays 10.0
```

Looking at the generated wrapper, the getproperty function `Base.getproperty(x::Data, f::Symbol)` uses the following address to get time https://github.com/JamieMair/MuJoCo.jl/blob/41df649223b4d56cf05cd072ef8e2d3da133f5b8/src/wrappers.jl#L4854

but the setproperty function ` Base.setproperty!(x::Data, f::Symbol, value)` does
https://github.com/JamieMair/MuJoCo.jl/blob/41df649223b4d56cf05cd072ef8e2d3da133f5b8/src/wrappers.jl#L6264-L6267

Both seem to get the internal_pointer the same way
https://github.com/JamieMair/MuJoCo.jl/blob/41df649223b4d56cf05cd072ef8e2d3da133f5b8/src/wrappers.jl#L4824-L4825
https://github.com/JamieMair/MuJoCo.jl/blob/41df649223b4d56cf05cd072ef8e2d3da133f5b8/src/wrappers.jl#L6171-L6172

Should these be the same? I tried manually calling `unsafe_store!(Ptr{Float64}(data.internal_pointer + 161616), t)` and that seemed to create the expected behavior for `data.time = t`. This may affect other fields in data and possibly other structs, I haven't checked. Thanks for your help!

I ran into this issue a while ago, but it hit again when trying to see why my visual global option to set the azimuth of the camera wasn't being loaded. Seems like the same thing may exists there as well

https://github.com/JamieMair/MuJoCo.jl/blob/41df649223b4d56cf05cd072ef8e2d3da133f5b8/src/visualiser_wrappers.jl#L424
https://github.com/JamieMair/MuJoCo.jl/blob/41df649223b4d56cf05cd072ef8e2d3da133f5b8/src/visualiser_wrappers.jl#L451-L455

**Comment by JamieMair** [comment]
Hi @arunleob, thanks for the bug report, it was very helpful! This must have snuck in when updating to MuJoCo 3. 

I've added a test for your example and it should be fixed now by https://github.com/JamieMair/MuJoCo.jl/pull/117. I will push the release after the CI is finished and the fix should be available later today.

**Comment by arunleob** [comment]
Thank you, really appreciate the quick reply and fix!
