### ISSUE TITLE
Data possibly incorrectly copied?

### ISSUE THREAD

**Issue by nic-barbara** [JamieMair/MuJoCo.jl#13]
@JamieMair  In the following example:

```julia
using MuJoCo

# Load a model and data
m = load_xml("../models/humanoid.xml")
d = init_data(m)

println(m.opt.timestep)
println(m.opt.gravity)
```
I'd expect the result to be
```
0.005
[0.0, 0.0, -9.81]
```
given the data in the `humanoid.xml` file (time step is set up the top). Instead, the output I get is the following:
```
1.999159027354971e37
[5.1964474e-315, 0.0, 4.2769804971223216e86]
```
Is there something funky going on with accessing/copying the data via UnsafeArrays?

**Comment by JamieMair** [comment]
Yes, I was sceptical about this as well! I think there's something off with the pointers. It's something I was trying to investigate for the controllers, but I'll have another look.

**Comment by nic-barbara** [comment]
Fixed in https://github.com/JamieMair/MuJoCo.jl/pull/19
