### ISSUE TITLE
Add in documentation for the underlying mujoco API

### ISSUE THREAD

**Issue by JamieMair** [JamieMair/MuJoCo.jl#23]
Related to https://github.com/JamieMair/MuJoCo.jl/issues/22.

The underlying mujoco API has some docs which are scraped from the mujoco `introspect` library. It may be worth documenting this in our documentation pages, along with linking to official docs.

**Comment by JamieMair** [comment]
Some of the initial work has been done in https://github.com/JamieMair/MuJoCo.jl/pull/53.

**Comment by nic-barbara** [comment]
@JamieMair what did you have in mind for this? The documentation in https://github.com/JamieMair/MuJoCo.jl/pull/64 includes links to DeepMind's documentation where relevant. What extra docs would we need for the underlying C API?

**Comment by JamieMair** [comment]
I think this is great for now. I think that merging https://github.com/JamieMair/MuJoCo.jl/pull/64 should close this issue.
