### ISSUE TITLE
Some `Data` fields not mapped to unsafe arrays

### ISSUE THREAD

**Issue by nic-barbara** [JamieMair/MuJoCo.jl#29]
There cases where fields of `mjData` are only filled after the first call of `mj_forward(m,d)` (which is called within `mj_step`). For example, the constraint Jacobian (which is pretty crucial for things like inverse-dynamics controllers) is stored in `d.efc_J`.  Here's an example with the humanoid:

```julia
using MuJoCo

# Load a model and check out constraint Jacobian
model = load_xml("models/humanoid.xml")
data = init_data(model)
J = unsafe_wrap(Vector{Float64}, data.efc_J, data.nnzJ, own=false)

println(data.efc_J)        # Prints: Ptr{Float64} @0x0000000000000000
println(J)                 # Prints: Float64[]

# Step it once and check again
step!(model, data)
J1 = unsafe_wrap(Vector{Float64}, data.efc_J, data.nnzJ, own=false)

println(data.efc_J)        # Prints: Ptr{Float64} @0x00007faeacf73fc8
println(J1)                # Prints: 864-element Vector{Float64} full of stuff
```

It would be nice to initialise an empty unsafe array for these objects so that we can still access them the same way as things like `data.qpos`. Note that this won't be a problem with models like cartpole, which don't actually have any constraint forces.

**Comment by nic-barbara** [comment]
Related to this (but certainly not essential for now) it would be great to have a few utils functions that convert the arrays `data.efc_J` and `data.qM` (the mass matrix, probably the most important of the lot for control purposes) to sparse/dense matrices. Currently MuJoCo stores them as vectors, and it's up to the user to reshape them and handle them as they see fit.

Note that MuJoCo stores all its sparse matrices in CSR not CSC format, which Julia uses (see [here](https://en.wikipedia.org/wiki/Sparse_matrix)).

**Comment by JamieMair** [comment]
> Related to this (but certainly not essential for now) it would be great to have a few utils functions that convert the arrays `data.efc_J` and `data.qM` (the mass matrix, probably the most important of the lot for control purposes) to sparse/dense matrices. Currently MuJoCo stores them as vectors, and it's up to the user to reshape them and handle them as they see fit.
> 
> Note that MuJoCo stores all its sparse matrices in CSR not CSC format, which Julia uses (see [here](https://en.wikipedia.org/wiki/Sparse_matrix)).

These conversions would be useful, and probably deserve their own issue as there is not a nice way to auto-generate them. I have opened a new issue - https://github.com/JamieMair/MuJoCo.jl/issues/30 - for this.

**Comment by JamieMair** [comment]
I'll try and look into why `data.efc_J` returns a pointer - the information exists, but isn't used.

**Comment by JamieMair** [comment]
Fixed by https://github.com/JamieMair/MuJoCo.jl/pull/32
