### ISSUE TITLE
Allow a nicer access to the names of the bodies for a loaded model

### ISSUE THREAD

**Issue by JamieMair** [JamieMair/MuJoCo.jl#49]

**Comment by nic-barbara** [comment]
[This](https://github.com/deepmind/mujoco/blob/main/python/mujoco/indexers.cc#L140) is how they do things in the Python bindings to get (for example) IDs from a body/geom/etc... name.

More explanation of the named access [here](https://mujoco.readthedocs.io/en/stable/python.html#named-access)
