### ISSUE TITLE
Find better names for the structs that wrap MuJoCo's C pointers.

### ISSUE THREAD

**Issue by JamieMair** [JamieMair/MuJoCo.jl#7]
Currently we use `Model` and `Data` to wrap a C pointer to `mjModel` and `mjData` structs, as this better follows Julia's struct naming guidelines. However, these names are not overly descriptive. They likely should be renamed at some point in the future, before a public release.

**Comment by nic-barbara** [comment]
I think the more we can align the names of structs and functions with the python bindings, the better it will be (within reason). We want it to be easy to go between the C, Python, and Julia interfaces.

**Comment by nic-barbara** [comment]
We can add `Engine` in the visualiser to the list. A more descriptive name would probably be more appropriate here.

**Comment by nic-barbara** [comment]
@JamieMair should we close this issue? I’ve gotten used to them now and it’s pretty reasonable to use Model and Data.
